/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.gui;

import adisys.server.presentation.frontController.Fc;
import adisys.server.presentation.frontController.FrontController;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * The Class DialogoVerifica.
 * Finestra contenente la visualizzazione dei contenuti 
 * di un file di interscambio prodotto da ADISys Mobile 
 * con i risultati grafici e numerici dell’analisi dei 
 * dati dell’accelerometro e GPS.
 * 
 */
public class DialogoVerifica extends javax.swing.JDialog {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The window. */
	private static DialogoVerifica window;

	/** The i fc. */
	private FrontController iFc = Fc.getInstance();

	/**
	 * Creates new form DialogoVerifica.
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            the modal
	 */
	public DialogoVerifica(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "rawtypes" })
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		immagineTestataVerifica = new javax.swing.JLabel();
		pannelloTabellaAttivita = new javax.swing.JScrollPane();
		tabellaAttivita = new javax.swing.JTable();
		pannelloTabellaLog = new javax.swing.JScrollPane();
		tabellaLog = new javax.swing.JTable();
		txInfermiere = new javax.swing.JLabel();
		txInfermiere1 = new javax.swing.JLabel();
		jToolBar1 = new javax.swing.JToolBar();
		pulsanteAggiornaLista = new javax.swing.JButton();
		cbFileJournaling = new javax.swing.JComboBox();
		pulsanteCarica = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setIconImage(null);
		setMinimumSize(new java.awt.Dimension(800, 600));
		setModal(true);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		immagineTestataVerifica
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/decorazioniFinestre/Verifica.png"))); // NOI18N

		tabellaAttivita.setRowHeight(25);
		tabellaAttivita
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaAttivita.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tabellaAttivitaMouseClicked(evt);
			}
		});
		tabellaAttivita.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				tabellaAttivitaKeyPressed(evt);
			}
		});
		pannelloTabellaAttivita.setViewportView(tabellaAttivita);

		tabellaLog
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaLog.getTableHeader().setReorderingAllowed(false);
		pannelloTabellaLog.setViewportView(tabellaLog);

		txInfermiere.setFont(txInfermiere.getFont().deriveFont(
				txInfermiere.getFont().getStyle() | java.awt.Font.BOLD, 14));
		txInfermiere.setForeground(new java.awt.Color(255, 255, 255));
		txInfermiere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		txInfermiere.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/barre/Viola.png"))); // NOI18N
		txInfermiere.setText(Fc.MessageBundle("UIMsg660")); // NOI18N
		txInfermiere
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		txInfermiere1.setFont(txInfermiere1.getFont().deriveFont(
				txInfermiere1.getFont().getStyle() | java.awt.Font.BOLD, 14));
		txInfermiere1.setForeground(new java.awt.Color(255, 255, 255));
		txInfermiere1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		txInfermiere1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/barre/Grigia.png"))); // NOI18N
		txInfermiere1.setText(Fc.MessageBundle("UIMsg690")); // NOI18N
		txInfermiere1
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);

		pulsanteAggiornaLista.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaAggiorna.png"))); // NOI18N
		pulsanteAggiornaLista.setText(Fc.MessageBundle("UIMsg650")); // NOI18N
		pulsanteAggiornaLista
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteAggiornaListaActionPerformed(evt);
					}
				});
		jToolBar1.add(pulsanteAggiornaLista);

		cbFileJournaling.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbFileJournalingActionPerformed(evt);
			}
		});
		jToolBar1.add(cbFileJournaling);

		pulsanteCarica.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/IconaImportazione.png"))); // NOI18N
		pulsanteCarica.setText(Fc.MessageBundle("UIMsg670")); // NOI18N
		pulsanteCarica.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteCaricaActionPerformed(evt);
			}
		});
		jToolBar1.add(pulsanteCarica);

		jLabel1.setText(Fc.MessageBundle("UIMsg680")); // NOI18N

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/pulsanti/Home.png"))); // NOI18N
		jButton1.setToolTipText(Fc.MessageBundle("UIMsg95")); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(153, 0, 153));
		jLabel2.setText(Fc.MessageBundle("UIMsg640")); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(pannelloTabellaLog)
				.addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		txInfermiere)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel1))
												.addComponent(txInfermiere1))
								.addGap(0, 93, Short.MAX_VALUE))
				.addComponent(pannelloTabellaAttivita)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(immagineTestataVerifica)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										181,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														immagineTestataVerifica,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(8, 8, 8)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txInfermiere)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(pannelloTabellaAttivita,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										203,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(txInfermiere1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(pannelloTabellaLog,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										178, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Pulsante aggiorna lista action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteAggiornaListaActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteAggiornaListaActionPerformed

		// Popolamento lista
		// ADISysControllerVerifica.getListaJournaling(cbFileJournaling);
		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		ArrayList<Object> par = new ArrayList<>();

		// par = new ArrayList<Object>();
		par.add("JComboBox<String>");
		par.add((Object) cbFileJournaling);
		parametri.add(par);

		iFc.processRequest("getListaJournaling", parametri);

	}// GEN-LAST:event_pulsanteAggiornaListaActionPerformed

	/**
	 * Pulsante carica action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteCaricaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteCaricaActionPerformed

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		ArrayList<Object> par = new ArrayList<>();

		// par = new ArrayList<Object>();
		par.add("String");
		par.add((Object) cbFileJournaling.getSelectedItem());
		parametri.add(par);

		String msg = (String) iFc.processRequest("caricaFile", parametri);
		JOptionPane.showMessageDialog(null, msg);

		datiInfermiere();
		aggiornaTabellaAttivita();
	}// GEN-LAST:event_pulsanteCaricaActionPerformed

	/**
	 * Form window activated.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		ArrayList<Object> par = new ArrayList<>();

		// par = new ArrayList<Object>();
		par.add("JComboBox<String>");
		par.add((Object) cbFileJournaling);
		parametri.add(par);

		iFc.processRequest("getListaJournaling", parametri);
	}// GEN-LAST:event_formWindowActivated

	/**
	 * Tabella attivita mouse clicked.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void tabellaAttivitaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabellaAttivitaMouseClicked
		int valoreSelezionato = tabellaAttivita.getSelectedRow();
		if (valoreSelezionato != -1) {

			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			// par = new ArrayList<Object>();
			par.add("JTable");
			par.add((Object) tabellaLog);
			parametri.add(par);

			par.add("int");
			par.add((Object) valoreSelezionato);
			parametri.add(par);

			iFc.processRequest("popolaTabellaLog", parametri);
			tabellaLog = Fc.setTableHeaders(tabellaLog,
					"JTableVerificaDati-Log");
		}

	}// GEN-LAST:event_tabellaAttivitaMouseClicked

	/**
	 * Tabella attivita key pressed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void tabellaAttivitaKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabellaAttivitaKeyPressed

		if (evt.getKeyChar() == 'i' || evt.getKeyChar() == 'I') {
			int valoreSelezionato = tabellaAttivita.getSelectedRow();
			if (valoreSelezionato != -1) {
				// ADISysControllerVerifica.showInfoInterventoCompleto(valoreSelezionato);
				ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
				ArrayList<Object> par = new ArrayList<>();

				// par = new ArrayList<Object>();
				par.add("int");
				par.add((Object) valoreSelezionato);
				parametri.add(par);
				iFc.processRequest("showInfoInterventoCompleto", parametri);
			}
		}

	}// GEN-LAST:event_tabellaAttivitaKeyPressed

	/**
	 * J button1 action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		//
		setVisible(false);
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * Cb file journaling action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void cbFileJournalingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbFileJournalingActionPerformed
		//
	}// GEN-LAST:event_cbFileJournalingActionPerformed

	/**
	 * Form window closing.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		//
		int result = 0;
		if (!fieldsAreEmpty()) {
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg35"), Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
		} else {
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg30"), Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		}

		if (result == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
	}// GEN-LAST:event_formWindowClosing

	/**
	 * Start.
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogoVerifica.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			// @Override
			public void run() {
				window = new DialogoVerifica(new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit()
						.getScreenSize();
				window.setLocation(new Point((risoluzioneSchermo.width - window
						.getWidth()) / 2, (risoluzioneSchermo.height - window
						.getHeight()) / 2));
				window.setVisible(true);

			}
		});
	}

	/**
	 * Dati infermiere.
	 */
	public void datiInfermiere() {
		String stringaInf = Fc.MessageBundle("UImsg740");

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		ArrayList<Object> par = new ArrayList<>();

		par.add("JLabel");
		par.add((Object) txInfermiere);
		parametri.add(par);

		par = new ArrayList<Object>();
		par.add("String");
		par.add((Object) stringaInf);
		parametri.add(par);

		iFc.processRequest("getDatiInfermiere", parametri);
	}

	/**
	 * Aggiorna tabella attivita.
	 */
	public void aggiornaTabellaAttivita() {
		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		ArrayList<Object> par = new ArrayList<>();

		par.add("JTable");
		par.add((Object) tabellaAttivita);
		parametri.add(par);

		iFc.processRequest("popolaTabellaAttivita", parametri);

		// /Svuota la tabella dei log
		tabellaLog.setModel(new DefaultTableModel());
		tabellaAttivita = Fc.setTableHeaders(tabellaAttivita,
				"JTableVerificaDati-Attivita");
	}

	/**
	 * Stop.
	 */
	public void stop() {
		if (window != null) {
			window.dispose();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The cb file journaling. */
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbFileJournaling;

	/** The immagine testata verifica. */
	private javax.swing.JLabel immagineTestataVerifica;

	/** The j button1. */
	private javax.swing.JButton jButton1;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The j label2. */
	private javax.swing.JLabel jLabel2;

	/** The j tool bar1. */
	private javax.swing.JToolBar jToolBar1;

	/** The pannello tabella attivita. */
	private javax.swing.JScrollPane pannelloTabellaAttivita;

	/** The pannello tabella log. */
	private javax.swing.JScrollPane pannelloTabellaLog;

	/** The pulsante aggiorna lista. */
	private javax.swing.JButton pulsanteAggiornaLista;

	/** The pulsante carica. */
	private javax.swing.JButton pulsanteCarica;

	/** The tabella attivita. */
	private javax.swing.JTable tabellaAttivita;

	/** The tabella log. */
	private javax.swing.JTable tabellaLog;

	/** The tx infermiere. */
	private javax.swing.JLabel txInfermiere;

	/** The tx infermiere1. */
	private javax.swing.JLabel txInfermiere1;

	// End of variables declaration//GEN-END:variables

	/**
	 * Fields are empty.
	 * 
	 * @return true, if successful
	 */
	private boolean fieldsAreEmpty() {
		return true;
	}
}
