/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.gui;

import adisys.server.business.TOInfermiere;
import adisys.server.business.TOIntervento;
import adisys.server.business.TOPaziente;
import adisys.server.presentation.frontController.Fc;
import adisys.server.presentation.frontController.FrontController;
import adisys.server.utility.DateFormatConverter;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 * The Class EditorInterventi.
 * Finestra che permette di inserire, modificare 
 * o cancellare i dati relativi a uno o a tutti 
 * gli interventi. Al suo interno è possibile 
 * interfacciarsi (per poter inserire, modificare 
 * o cancellare i dati) con le finestre EditorPazienti, 
 * EditorInfermieri, EditorPatologie. 
 * 
 */
public class EditorInterventi extends javax.swing.JDialog {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The i fc. */
	private FrontController iFc = Fc.getInstance();

	/** The nomi patologie. */
	private String[] nomiPatologie;

	/** The flag modalita. */
	private String flagModalita;

	/** The flag intervento selezionato. */
	private String flagInterventoSelezionato;

	/**
	 * Creates new form EditorInterventi.
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            the modal
	 */
	public EditorInterventi(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		nomiPatologie = (String[]) iFc.processRequest("getNomiPatologie",
				parametri);

		initComponents();
		aggiornaTabelle();
		setModalitaAggiungi();

	}

	/**
	 * Metodo che inizializza il form insieme al costruttore WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		immagineTestataInterventi = new javax.swing.JLabel();
		pannelloDati = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		txCitta = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		txCivico = new javax.swing.JTextField();
		txData = new javax.swing.JFormattedTextField();
		txCAP = new javax.swing.JFormattedTextField();
		jLabel12 = new javax.swing.JLabel();
		txPazienteSelezionato = new javax.swing.JFormattedTextField();
		txInfermiereSelezionato = new javax.swing.JFormattedTextField();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		labelIntervento = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		txOra = new javax.swing.JFormattedTextField();
		txNomePaziente = new javax.swing.JTextField();
		txNomeInfermiere = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		pulsanteAggiungiTipo = new javax.swing.JButton();
		pulsanteRimuoviTipo = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		tabellaTipiIntervento = new javax.swing.JTable();
		pulsanteConferma = new javax.swing.JButton();
		jScrollPane7 = new javax.swing.JScrollPane();
		tabellaInterventi = new javax.swing.JTable();
		jToolBar1 = new javax.swing.JToolBar();
		jLabel1 = new javax.swing.JLabel();
		pulsanteAggiungi = new javax.swing.JButton();
		pulsanteModifica = new javax.swing.JButton();
		pulsanteCancella = new javax.swing.JButton();
		pulsanteCancellaTutti = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabellaPazienti = new javax.swing.JTable();
		labelPazienti = new javax.swing.JLabel();
		pulsanteImpostaPaziente = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tabellaInfermieri = new javax.swing.JTable();
		labelInfermieri = new javax.swing.JLabel();
		pulsanteImpostaInfermiere = new javax.swing.JButton();
		labelInterventi = new javax.swing.JLabel();
		jButtonApriPianificatore = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButtonApriPazienti = new javax.swing.JButton();
		jButtonApriInfermieri = new javax.swing.JButton();
		jButtonApriInterventi = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMinimumSize(new java.awt.Dimension(800, 600));
		setModal(true);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		immagineTestataInterventi
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/adisys/server/img/decorazioniFinestre/Interventi.png"))); // NOI18N
		immagineTestataInterventi.setName(""); // NOI18N

		pannelloDati.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel9.setText(Fc.MessageBundle("UIMsg490")); // NOI18N
		jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel10.setText(Fc.MessageBundle("UIMsg510")); // NOI18N
		jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel11.setText(Fc.MessageBundle("UIMsg520")); // NOI18N
		jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		txData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.DateFormatter(
						new java.text.SimpleDateFormat("dd/MM/yyyy"))));
		txData.setToolTipText("Inserire la data nel formato gg/mm/aaaa (es 23/09/2012)");
		txData.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txDataActionPerformed(evt);
			}
		});

		txCAP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(
						new java.text.DecimalFormat("00000"))));

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel12.setText(Fc.MessageBundle("UIMsg500")); // NOI18N
		jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		txPazienteSelezionato
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		txPazienteSelezionato.setEnabled(false);

		txInfermiereSelezionato
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		txInfermiereSelezionato.setEnabled(false);

		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel13.setText(Fc.MessageBundle("UIMsg470")); // NOI18N
		jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel14.setText(Fc.MessageBundle("UIMsg480")); // NOI18N
		jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		labelIntervento.setFont(labelIntervento.getFont().deriveFont(
				labelIntervento.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelIntervento.setForeground(new java.awt.Color(255, 255, 255));
		labelIntervento
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelIntervento.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/barre/Azzurra.png"))); // NOI18N
		labelIntervento.setText(Fc.MessageBundle("UIMsg460")); // NOI18N
		labelIntervento
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel15.setText("CAP");
		jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		txOra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.DateFormatter(
						new java.text.SimpleDateFormat("HH.mm"))));

		txNomePaziente.setEditable(false);

		txNomeInfermiere.setEditable(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText(Fc.MessageBundle("UIMsg530")); // NOI18N

		jComboBox1.setModel(new DefaultComboBoxModel(nomiPatologie));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		pulsanteAggiungiTipo.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/add.png"))); // NOI18N
		pulsanteAggiungiTipo
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteAggiungiTipoActionPerformed(evt);
					}
				});

		pulsanteRimuoviTipo.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/remove.png"))); // NOI18N
		pulsanteRimuoviTipo
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteRimuoviTipoActionPerformed(evt);
					}
				});

		tabellaTipiIntervento.setAutoCreateRowSorter(true);
		tabellaTipiIntervento.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] {

				}));
		tabellaTipiIntervento
				.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		tabellaTipiIntervento
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane3.setViewportView(tabellaTipiIntervento);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jComboBox1,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pulsanteAggiungiTipo,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				33,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pulsanteRimuoviTipo,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				33,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel3)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				28,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																pulsanteAggiungiTipo,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(4, 4, 4)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				pulsanteRimuoviTipo,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				33,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				48,
																				Short.MAX_VALUE))
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE))
										.addContainerGap()));

		pulsanteConferma
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/adisys/server/img/pulsanti/iconainserisciazzurra.png"))); // NOI18N
		pulsanteConferma.setText(Fc.MessageBundle("UIMsg550")); // NOI18N
		pulsanteConferma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteConfermaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pannelloDatiLayout = new javax.swing.GroupLayout(
				pannelloDati);
		pannelloDati.setLayout(pannelloDatiLayout);
		pannelloDatiLayout
				.setHorizontalGroup(pannelloDatiLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pannelloDatiLayout
										.createSequentialGroup()
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																pannelloDatiLayout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				pulsanteConferma))
														.addGroup(
																pannelloDatiLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				pannelloDatiLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								pannelloDatiLayout
																										.createSequentialGroup()
																										.addGroup(
																												pannelloDatiLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel10)
																														.addComponent(
																																jLabel11))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												pannelloDatiLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																pannelloDatiLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				txCitta)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				jLabel15)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				txCAP,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				53,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(
																																txCivico)))
																						.addGroup(
																								pannelloDatiLayout
																										.createSequentialGroup()
																										.addGap(5,
																												5,
																												5)
																										.addGroup(
																												pannelloDatiLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																pannelloDatiLayout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel9)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				txData,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				100,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel12)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				txOra,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				47,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(0,
																																				33,
																																				Short.MAX_VALUE))
																														.addGroup(
																																pannelloDatiLayout
																																		.createSequentialGroup()
																																		.addGroup(
																																				pannelloDatiLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								jLabel14)
																																						.addComponent(
																																								jLabel13))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addGroup(
																																				pannelloDatiLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								txPazienteSelezionato)
																																						.addComponent(
																																								txInfermiereSelezionato,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								96,
																																								javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				pannelloDatiLayout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								txNomeInfermiere)
																																						.addComponent(
																																								txNomePaziente)))
																														.addComponent(
																																labelIntervento,
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)))
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))))
										.addContainerGap()));
		pannelloDatiLayout
				.setVerticalGroup(pannelloDatiLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								pannelloDatiLayout
										.createSequentialGroup()
										.addComponent(labelIntervento)
										.addGap(5, 5, 5)
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txPazienteSelezionato,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txNomePaziente,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(4, 4, 4)
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txInfermiereSelezionato,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txNomeInfermiere,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txData,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txOra,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																txCitta,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txCAP,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												pannelloDatiLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																txCivico,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pulsanteConferma)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jScrollPane7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		tabellaInterventi.setAutoCreateRowSorter(true);
		tabellaInterventi.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { {}, {}, {}, {} }, new String[] {

				}));
		tabellaInterventi
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaInterventi.getTableHeader().setReorderingAllowed(false);
		jScrollPane7.setViewportView(tabellaInterventi);

		jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jToolBar1.setFloatable(false);

		jLabel1.setFont(jLabel1.getFont().deriveFont(
				jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 12));
		jLabel1.setText(Fc.MessageBundle("UIMsg350")); // NOI18N
		jToolBar1.add(jLabel1);

		pulsanteAggiungi
				.setFont(pulsanteAggiungi.getFont().deriveFont(
						pulsanteAggiungi.getFont().getStyle()
								| java.awt.Font.BOLD, 12));
		pulsanteAggiungi.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaAggiungi.png"))); // NOI18N
		pulsanteAggiungi.setText(Fc.MessageBundle("UIMsg360")); // NOI18N
		pulsanteAggiungi.setFocusable(false);
		pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteAggiungiActionPerformed(evt);
			}
		});
		jToolBar1.add(pulsanteAggiungi);

		pulsanteModifica
				.setFont(pulsanteModifica.getFont().deriveFont(
						pulsanteModifica.getFont().getStyle()
								| java.awt.Font.BOLD, 12));
		pulsanteModifica.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaModifica.png"))); // NOI18N
		pulsanteModifica.setText(Fc.MessageBundle("UIMsg370")); // NOI18N
		pulsanteModifica.setFocusable(false);
		pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteModificaActionPerformed(evt);
			}
		});
		jToolBar1.add(pulsanteModifica);

		pulsanteCancella
				.setFont(pulsanteCancella.getFont().deriveFont(
						pulsanteCancella.getFont().getStyle()
								| java.awt.Font.BOLD, 12));
		pulsanteCancella.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaCancella.png"))); // NOI18N
		pulsanteCancella.setText(Fc.MessageBundle("UIMsg380")); // NOI18N
		pulsanteCancella.setFocusable(false);
		pulsanteCancella.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteCancellaActionPerformed(evt);
			}
		});
		jToolBar1.add(pulsanteCancella);

		pulsanteCancellaTutti.setFont(pulsanteCancellaTutti.getFont()
				.deriveFont(
						pulsanteCancellaTutti.getFont().getStyle()
								| java.awt.Font.BOLD, 12));
		pulsanteCancellaTutti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/IconaCancellaTutti.png"))); // NOI18N
		pulsanteCancellaTutti.setText(Fc.MessageBundle("UIMsg390")); // NOI18N
		pulsanteCancellaTutti.setFocusable(false);
		pulsanteCancellaTutti
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteCancellaTuttiActionPerformed(evt);
					}
				});
		jToolBar1.add(pulsanteCancellaTutti);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		tabellaPazienti.setAutoCreateRowSorter(true);
		tabellaPazienti.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { {}, {}, {}, {} }, new String[] {

				}));
		tabellaPazienti
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaPazienti.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(tabellaPazienti);

		labelPazienti.setFont(labelPazienti.getFont().deriveFont(
				labelPazienti.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelPazienti.setForeground(new java.awt.Color(255, 255, 255));
		labelPazienti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelPazienti.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/barre/Verde.png"))); // NOI18N
		labelPazienti.setText(Fc.MessageBundle("UIMsg420")); // NOI18N
		labelPazienti
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		pulsanteImpostaPaziente.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/miniinserisciverde.png"))); // NOI18N
		pulsanteImpostaPaziente.setText(Fc.MessageBundle("UIMsg430")); // NOI18N
		pulsanteImpostaPaziente
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteImpostaPaziente
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteImpostaPazienteActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE)
														.addComponent(
																pulsanteImpostaPaziente,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																345,
																Short.MAX_VALUE)
														.addComponent(
																labelPazienti,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(labelPazienti)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												109,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												pulsanteImpostaPaziente,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(95, 95, 95)));

		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		tabellaInfermieri.setAutoCreateRowSorter(true);
		tabellaInfermieri.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { {}, {}, {}, {} }, new String[] {

				}));
		tabellaInfermieri
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaInfermieri.getTableHeader().setReorderingAllowed(false);
		jScrollPane2.setViewportView(tabellaInfermieri);

		labelInfermieri.setFont(labelInfermieri.getFont().deriveFont(
				labelInfermieri.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelInfermieri.setForeground(new java.awt.Color(255, 255, 255));
		labelInfermieri
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelInfermieri.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/barre/Rossa.png"))); // NOI18N
		labelInfermieri.setText(Fc.MessageBundle("UIMsg440")); // NOI18N
		labelInfermieri
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		pulsanteImpostaInfermiere.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/miniinseriscirosso.png"))); // NOI18N
		pulsanteImpostaInfermiere.setText(Fc.MessageBundle("UIMsg450")); // NOI18N
		pulsanteImpostaInfermiere
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteImpostaInfermiere
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteImpostaInfermiereActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE)
														.addComponent(
																pulsanteImpostaInfermiere,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																labelInfermieri,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(labelInfermieri)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												113,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pulsanteImpostaInfermiere)
										.addGap(49, 49, 49)));

		labelInterventi.setFont(labelInterventi.getFont().deriveFont(
				labelInterventi.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelInterventi.setForeground(new java.awt.Color(255, 255, 255));
		labelInterventi
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelInterventi.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/barre/Azzurra.png"))); // NOI18N
		labelInterventi.setText(Fc.MessageBundle("UIMsg330")); // NOI18N
		labelInterventi
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jButtonApriPianificatore.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/Home.png"))); // NOI18N
		jButtonApriPianificatore.setToolTipText(Fc.MessageBundle("UIMsg95")); // NOI18N
		jButtonApriPianificatore
				.setPreferredSize(new java.awt.Dimension(53, 23));
		jButtonApriPianificatore
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPianificatoreActionPerformed(evt);
					}
				});

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 51, 255));
		jLabel2.setText(Fc.MessageBundle("UIMsg320")); // NOI18N

		jButtonApriPazienti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaPazienti.png"))); // NOI18N
		jButtonApriPazienti.setToolTipText(Fc.MessageBundle("UIMsg70")); // NOI18N
		jButtonApriPazienti.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriPazienti
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPazientiActionPerformed(evt);
					}
				});

		jButtonApriInfermieri
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInfermieri.png"))); // NOI18N
		jButtonApriInfermieri.setToolTipText(Fc.MessageBundle("UIMsg80")); // NOI18N
		jButtonApriInfermieri.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriInfermieri
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriInfermieriActionPerformed(evt);
					}
				});

		jButtonApriInterventi
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInterventi.png"))); // NOI18N
		jButtonApriInterventi.setEnabled(false);
		jButtonApriInterventi.setPreferredSize(new java.awt.Dimension(33, 33));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/pulsanti/IconaPatologie.png"))); // NOI18N
		jButton1.setToolTipText(Fc.MessageBundle("UIMsg65")); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jToolBar1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										immagineTestataInterventi)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										141,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						labelInterventi))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		33,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriPazienti,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriInfermieri,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriInterventi,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriPianificatore,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		33,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanel3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		pannelloDati,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addComponent(jScrollPane7))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						immagineTestataInterventi,
																						javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		7,
																		Short.MAX_VALUE)
																.addComponent(
																		labelInterventi,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		20,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(3, 3, 3))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jButtonApriPazienti,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriInfermieri,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriInterventi,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriPianificatore,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)))
								.addComponent(jScrollPane7,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jToolBar1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										25,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(4, 4, 4)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		184,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jPanel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		185,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														pannelloDati,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(14, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Pulsante aggiungi action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteAggiungiActionPerformed
		// if (txModalita.getText().equals(modAggiungi)) {
		if (flagModalita.equals(modAggiungi)) {
			JOptionPane.showMessageDialog(null,
					Fc.MessageBundle("MsgDialog1940"),
					Fc.MessageBundle("MsgDialog4"),
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			setModalitaAggiungi();
		}// GEN-LAST:event_pulsanteAggiungiActionPerformed
	}

	/**
	 * Pulsante modifica action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteModificaActionPerformed
		setModalitaModifica();

	}// GEN-LAST:event_pulsanteModificaActionPerformed

	/**
	 * Form window activated.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		// Aggiornamento tabelle al ritorno dai popup
		aggiornaTabelle();
	}// GEN-LAST:event_formWindowActivated

	/**
	 * Pulsante cancella tutti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteCancellaTuttiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteCancellaTuttiActionPerformed

		if (JOptionPane.showConfirmDialog(null,
				Fc.MessageBundle("ConfirmMsg240"),
				Fc.MessageBundle("ConfirmMsg10"), JOptionPane.OK_CANCEL_OPTION,
				JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {

			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			iFc.processRequest("cancellaTuttiInterventi", parametri);
		}
	}// GEN-LAST:event_pulsanteCancellaTuttiActionPerformed

	/**
	 * Pulsante imposta paziente action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteImpostaPazienteActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteImpostaPazienteActionPerformed

		int riga = tabellaPazienti.getSelectedRow();
		String[] colonne = Fc
				.getTableHeaderNames("JTableEditorInterventi-Pazienti");
		// Verifica selezione paziente
		if (riga == -1) {
			// Caso selezione nulla
			JOptionPane.showMessageDialog(null, Fc.MessageBundle("MsgDialog70")
					+ "\n" + Fc.MessageBundle("MsgDialog35"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);

		} else {
			// Caso selezione valida

			// recupero dei numeri di colonna
			int colonnaID = tabellaPazienti.getColumn(colonne[0])
					.getModelIndex();
			int colonnaNome = tabellaPazienti.getColumn(colonne[1])
					.getModelIndex();
			int colonnaCognome = tabellaPazienti.getColumn(colonne[2])
					.getModelIndex();

			// Set della variabile relativa al paziente selezionato
			txPazienteSelezionato.setValue(Integer.valueOf(String
					.valueOf(tabellaPazienti.getValueAt(riga, colonnaID))));

			// Set campo nomepaziente
			String tNome = String.valueOf(tabellaPazienti.getValueAt(riga,
					colonnaNome));
			String tCognome = String.valueOf(tabellaPazienti.getValueAt(riga,
					colonnaCognome));
			txNomePaziente.setText(tNome + " " + tCognome);

			// Notifica
			String notifica = Fc.MessageBundle("MsgDialog80");

			notifica += txPazienteSelezionato.getText() + ".";
			notifica += "\n " + Fc.MessageBundle("MsgDialog90") + ": " + tNome;
			notifica += "\n " + Fc.MessageBundle("MsgDialog100") + ": "
					+ tCognome;

			JOptionPane.showMessageDialog(null, notifica);
		}
	}// GEN-LAST:event_pulsanteImpostaPazienteActionPerformed

	/**
	 * Pulsante imposta infermiere action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteImpostaInfermiereActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteImpostaInfermiereActionPerformed
		// Recupero riga selezione
		int riga = tabellaInfermieri.getSelectedRow();
		String[] colonne = Fc
				.getTableHeaderNames("JTableEditorInterventi-Infermieri");
		// Verifica selezione infermiere
		if (riga == -1) {
			// Caso selezione nulla

			JOptionPane.showMessageDialog(
					null,
					Fc.MessageBundle("MsgDialog110") + "\n"
							+ Fc.MessageBundle("MsgDialog45"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);
		} else {
			// Caso selezione valida

			// recupero dei numeri di colonna
			int colonnaID = tabellaInfermieri.getColumn(colonne[0])
					.getModelIndex();
			int colonnaNome = tabellaInfermieri.getColumn(colonne[1])
					.getModelIndex();
			int colonnaCognome = tabellaInfermieri.getColumn(colonne[2])
					.getModelIndex();

			// Set della variabile relativa all'infermiere selezionato
			txInfermiereSelezionato.setValue(Integer.valueOf(String
					.valueOf(tabellaInfermieri.getValueAt(riga, colonnaID))));

			// Set campo nomeinfermiere
			String tNome = String.valueOf(tabellaInfermieri.getValueAt(riga,
					colonnaNome));
			String tCognome = String.valueOf(tabellaInfermieri.getValueAt(riga,
					colonnaCognome));
			txNomeInfermiere.setText(tNome + " " + tCognome);

			// Notifica
			String notifica = Fc.MessageBundle("MsgDialog120");
			notifica += txInfermiereSelezionato.getText() + ".";
			notifica += "\n " + Fc.MessageBundle("MsgDialog90") + ": " + tNome;
			notifica += "\n " + Fc.MessageBundle("MsgDialog100") + ": "
					+ tCognome;

			JOptionPane.showMessageDialog(null, notifica);
		}
	}// GEN-LAST:event_pulsanteImpostaInfermiereActionPerformed

	/**
	 * Pulsante cancella action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteCancellaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteCancellaActionPerformed

		String[] colonne = Fc
				.getTableHeaderNames("JTableEditorInterventi-Interventi");
		if (tabellaInterventi.getSelectedRow() != -1) {
			if (JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg220"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {

				Object id = Integer.parseInt(String.valueOf(tabellaInterventi
						.getValueAt(tabellaInterventi.getSelectedRow(),
								tabellaInterventi.getColumn(colonne[0])
										.getModelIndex())));
				ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
				ArrayList<Object> par = new ArrayList<>();

				par.add("int");
				par.add(id);
				parametri.add(par);

				iFc.processRequest("cancellaIntervento", parametri);
			}
		} else {
			JOptionPane.showMessageDialog(
					null,
					Fc.MessageBundle("MsgDialog135") + "\n"
							+ Fc.MessageBundle("MsgDialog25"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_pulsanteCancellaActionPerformed

	/**
	 * Pulsante rimuovi tipo action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteRimuoviTipoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteRimuoviTipoActionPerformed
		if (tabellaTipiIntervento.getSelectedRowCount() > 0) {
			if (JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg45"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
				modelloTipiIntervento.removeRow(tabellaTipiIntervento
						.getSelectedRow());
			}
		} else {
			JOptionPane.showMessageDialog(null,
					Fc.MessageBundle("MsgDialog95"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_pulsanteRimuoviTipoActionPerformed

	/**
	 * Pulsante aggiungi tipo action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteAggiungiTipoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteAggiungiTipoActionPerformed
		// TEST Chiamata finestra di dialogo
		// String[] rigaVuota={"",""};
		modelloTipiIntervento
				.setRowCount(modelloTipiIntervento.getRowCount() + 1);
		modelloTipiIntervento.setValueAt(jComboBox1.getSelectedItem(),
				modelloTipiIntervento.getRowCount() - 1, 0);

	}// GEN-LAST:event_pulsanteAggiungiTipoActionPerformed

	/**
	 * J combo box1 action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		//
	}// GEN-LAST:event_jComboBox1ActionPerformed

	/**
	 * Pulsante conferma action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteConfermaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteConfermaActionPerformed
		// RECUPERO DATI DAL MODULO
		String idPaziente = txPazienteSelezionato.getText();
		String idInfermiere = txInfermiereSelezionato.getText();

		String citta = txCitta.getText();
		String civico = txCivico.getText();
		String cap = txCAP.getText();

		String data = txData.getText();
		String ora = txOra.getText();

		DefaultTableModel modelloTabellaTipi = (DefaultTableModel) tabellaTipiIntervento
				.getModel();

		if (flagModalita.equals(modAggiungi)) {

			// Caso nuovo intervento
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			// par = new ArrayList<Object>();
			par.add("String");
			par.add((Object) idPaziente);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) idInfermiere);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) citta);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) civico);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) cap);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) data);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) ora);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("DefaultTableModel");
			par.add((Object) modelloTabellaTipi);
			parametri.add(par);

			iFc.processRequest("creaIntervento", parametri);

		} else if (flagModalita.equals(modModifica)
				&& JOptionPane.showConfirmDialog(null,
						Fc.MessageBundle("ConfirmMsg210"),
						Fc.MessageBundle("ConfirmMsg100"),
						JOptionPane.OK_CANCEL_OPTION,
						JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
			// Caso modifica intervento
			// int id = Integer.parseInt(txInterventoSelezionato.getText());
			int id = Integer.valueOf(flagInterventoSelezionato);

			// chiamata controller
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			// par = new ArrayList<Object>();
			par.add("int");
			par.add((Object) id);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) idPaziente);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) idInfermiere);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) citta);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) civico);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) cap);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) data);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) ora);
			parametri.add(par);

			par = new ArrayList<>();
			par.add("DefaultTableModel");
			par.add((Object) modelloTabellaTipi);
			parametri.add(par);

			iFc.processRequest("modificaIntervento", parametri);
		}
	}// GEN-LAST:event_pulsanteConfermaActionPerformed

	/**
	 * J button1 action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg15"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			iFc.processRequest("visualizzaEditorPatologie",
					new ArrayList<ArrayList<Object>>());
			this.setVisible(false);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * J button apri pianificatore action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPianificatoreActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPianificatoreActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg25"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			setVisible(false);
		}
	}// GEN-LAST:event_jButtonApriPianificatoreActionPerformed

	/**
	 * Tx data action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void txDataActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txDataActionPerformed
		//
	}// GEN-LAST:event_txDataActionPerformed

	/**
	 * Form window closing.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		int result = 0;
		if (!fieldsAreEmpty())
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg35"), Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
		else
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg30"),Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

		if (result == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
	}// GEN-LAST:event_formWindowClosing

	/**
	 * J button apri pazienti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPazientiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPazientiActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg15"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			setVisible(false);
			iFc.processRequest("visualizzaEditorPazienti",
					new ArrayList<ArrayList<Object>>());
		}
	}// GEN-LAST:event_jButtonApriPazientiActionPerformed

	/**
	 * J button apri infermieri action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriInfermieriActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriInfermieriActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg15"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			setVisible(false);
			iFc.processRequest("visualizzaEditorInfermieri",
					new ArrayList<ArrayList<Object>>());
		}
	}// GEN-LAST:event_jButtonApriInfermieriActionPerformed

	/**
	 * Aggiorna tabelle.
	 */
	private void aggiornaTabelle() {

		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOIntervento> listaInterventi = (ArrayList<TOIntervento>) iFc
				.processRequest("getTabellaInterventi");
		TOIntervento toIntervento;
		DefaultTableModel modelIntervento = new DefaultTableModel();

		// Assegnazione nomi colonne tabella interventi
		String[] headersIntervento = Fc
				.getTableHeaderNames("JTableEditorInterventi-Interventi");
		modelIntervento.setColumnIdentifiers(headersIntervento);

		// inserimento dei transfer objects nella tabella interventi
		int tLengthIntervento = listaInterventi.size();
		for (int i = 0; i < tLengthIntervento; i++) {
			toIntervento = listaInterventi.get(i);
			String[] row = { String.valueOf(toIntervento.getID()),
					String.valueOf(toIntervento.getIDInfermiere()),
					String.valueOf(toIntervento.getIDPaziente()),
					toIntervento.getCitta(), toIntervento.getCivico(),
					toIntervento.getCap(), toIntervento.getData("yyyy-MM-dd"),
					toIntervento.getOraInizio("HH:mm:ss") };
			modelIntervento.addRow(row);
		}
		tabellaInterventi.setModel(modelIntervento);

		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOInfermiere> listaInfermieri = (ArrayList<TOInfermiere>) iFc
				.processRequest("getTabellaInfermieri",
						new ArrayList<ArrayList<Object>>());
		TOInfermiere toInfermiere;
		DefaultTableModel model = new DefaultTableModel();

		// Assegnazione nomi colonne tabella infermieri
		String[] headers = Fc
				.getTableHeaderNames("JTableEditorInterventi-Infermieri");
		model.setColumnIdentifiers(headers);

		// inserimento dei transfer objects nella tabella infermieri
		int tLength = listaInfermieri.size();
		for (int i = 0; i < tLength; i++) {
			toInfermiere = listaInfermieri.get(i);
			String[] row = { String.valueOf(toInfermiere.getID()),
					toInfermiere.getNome(), toInfermiere.getCognome() };
			model.addRow(row);
		}
		tabellaInfermieri.setModel(model);

		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOPaziente> listaPazienti = (ArrayList<TOPaziente>) iFc
				.processRequest("getTabellaPazienti");
		TOPaziente toPaziente;
		DefaultTableModel modelPaziente = new DefaultTableModel();

		// Assegnazione nomi colonne tabella pazienti
		String[] headersPaziente = Fc
				.getTableHeaderNames("JTableEditorInterventi-Pazienti");
		modelPaziente.setColumnIdentifiers(headersPaziente);

		// inserimento dei transfer objects nella tabella pazienti
		int tLengthPaziente = listaPazienti.size();
		for (int i = 0; i < tLengthPaziente; i++) {
			toPaziente = listaPazienti.get(i);
			String[] row = { String.valueOf(toPaziente.getID()),
					toPaziente.getNome(), toPaziente.getCognome(),
					toPaziente.getDataNascita("yyyy-MM-dd") };
			modelPaziente.addRow(row);
		}
		tabellaPazienti.setModel(modelPaziente);

	}

	/**
	 * Start.
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void start(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger
					.getLogger(EditorInterventi.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			// @Override
			public void run() {
				EditorInterventi window = new EditorInterventi(
						new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit()
						.getScreenSize();
				window.setLocation(new Point((risoluzioneSchermo.width - window
						.getWidth()) / 2, (risoluzioneSchermo.height - window
						.getHeight()) / 2));
				window.setVisible(true);
				window.aggiornaTabelle();
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The immagine testata interventi. */
	private javax.swing.JLabel immagineTestataInterventi;

	/** The j button1. */
	private javax.swing.JButton jButton1;

	/** The j button apri infermieri. */
	private javax.swing.JButton jButtonApriInfermieri;

	/** The j button apri interventi. */
	private javax.swing.JButton jButtonApriInterventi;

	/** The j button apri pazienti. */
	private javax.swing.JButton jButtonApriPazienti;

	/** The j button apri pianificatore. */
	private javax.swing.JButton jButtonApriPianificatore;

	/** The j combo box1. */
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The j label10. */
	private javax.swing.JLabel jLabel10;

	/** The j label11. */
	private javax.swing.JLabel jLabel11;

	/** The j label12. */
	private javax.swing.JLabel jLabel12;

	/** The j label13. */
	private javax.swing.JLabel jLabel13;

	/** The j label14. */
	private javax.swing.JLabel jLabel14;

	/** The j label15. */
	private javax.swing.JLabel jLabel15;

	/** The j label2. */
	private javax.swing.JLabel jLabel2;

	/** The j label3. */
	private javax.swing.JLabel jLabel3;

	/** The j label9. */
	private javax.swing.JLabel jLabel9;

	/** The j panel1. */
	private javax.swing.JPanel jPanel1;

	/** The j panel2. */
	private javax.swing.JPanel jPanel2;

	/** The j panel3. */
	private javax.swing.JPanel jPanel3;

	/** The j scroll pane1. */
	private javax.swing.JScrollPane jScrollPane1;

	/** The j scroll pane2. */
	private javax.swing.JScrollPane jScrollPane2;

	/** The j scroll pane3. */
	private javax.swing.JScrollPane jScrollPane3;

	/** The j scroll pane7. */
	private javax.swing.JScrollPane jScrollPane7;

	/** The j tool bar1. */
	private javax.swing.JToolBar jToolBar1;

	/** The label infermieri. */
	private javax.swing.JLabel labelInfermieri;

	/** The label interventi. */
	private javax.swing.JLabel labelInterventi;

	/** The label intervento. */
	private javax.swing.JLabel labelIntervento;

	/** The label pazienti. */
	private javax.swing.JLabel labelPazienti;

	/** The pannello dati. */
	private javax.swing.JPanel pannelloDati;

	/** The pulsante aggiungi. */
	private javax.swing.JButton pulsanteAggiungi;

	/** The pulsante aggiungi tipo. */
	private javax.swing.JButton pulsanteAggiungiTipo;

	/** The pulsante cancella. */
	private javax.swing.JButton pulsanteCancella;

	/** The pulsante cancella tutti. */
	private javax.swing.JButton pulsanteCancellaTutti;

	/** The pulsante conferma. */
	private javax.swing.JButton pulsanteConferma;

	/** The pulsante imposta infermiere. */
	private javax.swing.JButton pulsanteImpostaInfermiere;

	/** The pulsante imposta paziente. */
	private javax.swing.JButton pulsanteImpostaPaziente;

	/** The pulsante modifica. */
	private javax.swing.JButton pulsanteModifica;

	/** The pulsante rimuovi tipo. */
	private javax.swing.JButton pulsanteRimuoviTipo;

	/** The tabella infermieri. */
	private javax.swing.JTable tabellaInfermieri;

	/** The tabella interventi. */
	private javax.swing.JTable tabellaInterventi;

	/** The tabella pazienti. */
	private javax.swing.JTable tabellaPazienti;

	/** The tabella tipi intervento. */
	private javax.swing.JTable tabellaTipiIntervento;

	/** The tx cap. */
	private javax.swing.JFormattedTextField txCAP;

	/** The tx citta. */
	private javax.swing.JTextField txCitta;

	/** The tx civico. */
	private javax.swing.JTextField txCivico;

	/** The tx data. */
	private javax.swing.JFormattedTextField txData;

	/** The tx infermiere selezionato. */
	private javax.swing.JFormattedTextField txInfermiereSelezionato;

	/** The tx nome infermiere. */
	private javax.swing.JTextField txNomeInfermiere;

	/** The tx nome paziente. */
	private javax.swing.JTextField txNomePaziente;

	/** The tx ora. */
	private javax.swing.JFormattedTextField txOra;

	/** The tx paziente selezionato. */
	private javax.swing.JFormattedTextField txPazienteSelezionato;
	// End of variables declaration//GEN-END:variables
	/** The modello tipi intervento. */
	private DefaultTableModel modelloTipiIntervento;

	/**
	 * Prepara il modulo per l'inserimento di un nuovo intervento.
	 */
	private void setModalitaAggiungi() {

		// RESET DEGLI INDICI DI PAZIENTE ED INFERMIERE
		// txModalita.setText(modAggiungi);
		flagModalita = modAggiungi;

		// txInterventoSelezionato.setText(null);
		flagInterventoSelezionato = null;
		txInfermiereSelezionato.setText(null);
		txPazienteSelezionato.setText(null);

		// RESET SELEZIONI TABELLA
		tabellaPazienti.clearSelection();
		tabellaInfermieri.clearSelection();
		tabellaInterventi.clearSelection();

		// RESET DEI CAMPI DI INSERIMENTO
		txData.setText("");
		txOra.setText("");

		txCAP.setText("");
		txCitta.setText("");
		txCivico.setText("");

		// RESET ETICHETTE
		txNomePaziente.setText(Fc.MessageBundle("MsgDialog520"));
		txNomeInfermiere.setText(Fc.MessageBundle("MsgDialog530"));
		labelIntervento.setText(Fc.MessageBundle("MsgDialog540"));
		pulsanteConferma.setText(Fc.MessageBundle("MsgDialog550"));

		// Reset tipi Intervento
		String[] colonne = Fc
				.getTableHeaderNames("JTableEditorInterventi-Patologie");
		DefaultTableModel modelloTipi = new DefaultTableModel(colonne, 0);
		modelloTipiIntervento = modelloTipi;
		tabellaTipiIntervento.setModel(modelloTipiIntervento);

	}

	/**
	 * Se c'e' un intervento selezionato prepara il modulo per la modifica,
	 * altrimenti visualizza un messaggio di errore.
	 */
	private void setModalitaModifica() {
		// Se e' selezionato un valore nella tabella interventi prepara il
		// modulo
		// per la modifica. Altrimenti visualizza un messaggio di errore

		// VERIFICA INTERVENTO SELEZIONATO
		int rigaSelezionata = tabellaInterventi.getSelectedRow();

		if (rigaSelezionata == -1) {
			// NESSUNA RIGA SELEZIONATA
			JOptionPane.showMessageDialog(
					null,
					Fc.MessageBundle("MsgDialog130") + "\n"
							+ Fc.MessageBundle("MsgDialog65"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);
		} else {
			// RECUPERO INFO COLONNE
			String[] colonne = Fc
					.getTableHeaderNames("JTableEditorInterventi-Interventi");
			int colonnaID = tabellaInterventi.getColumn(colonne[0])
					.getModelIndex();
			int colonnaIDPaziente = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[1]);
			int colonnaIDInfermiere = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[2]);

			int colonnaData = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[6]);
			int colonnaOraInizio = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[7]);

			int colonnaCitta = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[3]);
			int colonnaCivico = tabellaInterventi.getColumnModel()
					.getColumnIndex(colonne[4]);
			int colonnaCAP = tabellaInterventi.getColumnModel().getColumnIndex(
					colonne[5]);

			// RECUPERO INFORMAZIONI ATTUALI E POPOLAMENTO CAMPI
			// txInterventoSelezionato.setText(tabellaInterventi.getValueAt(rigaSelezionata,
			// colonnaID).toString());
			flagInterventoSelezionato = (tabellaInterventi.getValueAt(
					rigaSelezionata, colonnaID).toString());
			txPazienteSelezionato.setText(tabellaInterventi.getValueAt(
					rigaSelezionata, colonnaIDPaziente).toString());
			txInfermiereSelezionato.setText(tabellaInterventi.getValueAt(
					rigaSelezionata, colonnaIDInfermiere).toString());

			txCitta.setText(tabellaInterventi.getValueAt(rigaSelezionata,
					colonnaCitta).toString());
			txCivico.setText(tabellaInterventi.getValueAt(rigaSelezionata,
					colonnaCivico).toString());
			txCAP.setText(tabellaInterventi.getValueAt(rigaSelezionata,
					colonnaCAP).toString());

			// Elaborazione data-ora
			// Cambiamento formato data e ora
			String testoData = DateFormatConverter.cambiaFormato(
					tabellaInterventi.getValueAt(rigaSelezionata, colonnaData)
							.toString(), "yyyy-MM-dd", "dd/MM/yyyy");
			String testoOra = DateFormatConverter.cambiaFormato(
					tabellaInterventi.getValueAt(rigaSelezionata,
							colonnaOraInizio).toString(), "HH:mm:ss", "HH.mm");

			// Trace
			System.out.println(Fc.MessageBundle("MsgDialog560") + (" ")
					+ testoData);
			System.out.println(Fc.MessageBundle("MsgDialog570") + (" ")
					+ testoOra);

			// Assegnazione dataOra
			txData.setText(testoData);
			txOra.setText(testoOra);

			String[] colonnePatologie = Fc
					.getTableHeaderNames("JTableEditorInterventi-Patologie");

			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			par.add("int");
			par.add((Object) Integer.valueOf(tabellaInterventi.getValueAt(
					rigaSelezionata, colonnaID).toString()));
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String[]");
			par.add((Object) colonnePatologie);
			parametri.add(par);

			modelloTipiIntervento = (DefaultTableModel) iFc.processRequest(
					"getTipiIntervento", parametri);

			// modelloTipiIntervento =
			// GestioneInterventi.getTipiIntervento(Integer.valueOf(tabellaInterventi.getValueAt(rigaSelezionata,
			// colonnaID).toString()), colonnePatologie);
			tabellaTipiIntervento.setModel(modelloTipiIntervento);

			// RESET ETICHETTE
			txNomePaziente.setText(Fc.MessageBundle("MsgDialog580"));
			txNomeInfermiere.setText(Fc.MessageBundle("MsgDialog590"));
			labelIntervento.setText(Fc.MessageBundle("MsgDialog600") + (" ")
					+ flagInterventoSelezionato);
			pulsanteConferma.setText(Fc.MessageBundle("ConfirmMsg250"));

			// Settaggio variabile di stato
			// txModalita.setText(modModifica);
			flagModalita = modModifica;
		}
	}

	/**
	 * Fields are empty.
	 * 
	 * @return true, if successful
	 */
	private boolean fieldsAreEmpty() {
		if (txData.getText().isEmpty() && txOra.getText().isEmpty()
				&& txCitta.getText().isEmpty() && txCAP.getText().isEmpty()
				&& txCivico.getText().isEmpty()) {
			return true;
		} else {
			return false;
		}
	}

	/** The mod aggiungi. */
	private final String modAggiungi = Fc.MessageBundle("MsgDialog610");

	/** The mod modifica. */
	private final String modModifica = Fc.MessageBundle("MsgDialog620");
}
