/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.gui;

import adisys.server.business.TOInfermiere;
import adisys.server.presentation.frontController.Fc;
import adisys.server.presentation.frontController.FrontController;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * The Class EditorInfermieri.
 * Finestra che permette di inserire, modificare o cancellare 
 * i dati relativi a uno o a tutti gli infermieri. E’ possibile 
 * interfacciarsi con la finestra EditorInterventi.
 * 
 */
public final class EditorInfermieri extends javax.swing.JDialog {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The i fc. */
	private FrontController iFc = Fc.getInstance();

	/**
	 * Creates new form dialogoInfermieri.
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            the modal
	 */
	public EditorInfermieri(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		aggiornaTabella();
		setAggiungiInfermiere();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		immagineTestataInfermieri = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		pulsanteCancella = new javax.swing.JButton();
		pulsanteModifica = new javax.swing.JButton();
		pulsanteAggiungi = new javax.swing.JButton();
		pulsanteCancellaTutti = new javax.swing.JButton();
		pannelloModifica = new javax.swing.JPanel();
		txNome = new javax.swing.JTextField();
		txCognome = new javax.swing.JTextField();
		pulsanteOK = new javax.swing.JButton();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txID = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txInfo = new javax.swing.JTextArea();
		jButtonApriPianificatore = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButtonApriInterventi = new javax.swing.JButton();
		jScrollPane8 = new javax.swing.JScrollPane();
		tabellaInfermieri = new javax.swing.JTable();
		jButtonApriInfermieri = new javax.swing.JButton();
		jButtonApriPazienti = new javax.swing.JButton();
		jButtonApriPatologie = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(640, 480));
		setModal(true);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		immagineTestataInfermieri
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/adisys/server/img/decorazioniFinestre/Infermieri.png"))); // NOI18N

		pulsanteCancella.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaCancella.png"))); // NOI18N
		pulsanteCancella.setText(Fc.MessageBundle("UIMsg590")); // NOI18N
		pulsanteCancella
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteCancella.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteCancellaActionPerformed(evt);
			}
		});

		pulsanteModifica.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaModifica.png"))); // NOI18N
		pulsanteModifica.setText(Fc.MessageBundle("UIMsg580")); // NOI18N
		pulsanteModifica
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteModificaActionPerformed(evt);
			}
		});

		pulsanteAggiungi.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaAggiungi.png"))); // NOI18N
		pulsanteAggiungi.setText(Fc.MessageBundle("UIMsg570")); // NOI18N
		pulsanteAggiungi
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteAggiungiActionPerformed(evt);
			}
		});

		pulsanteCancellaTutti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/IconaCancellaTutti.png"))); // NOI18N
		pulsanteCancellaTutti.setText(Fc.MessageBundle("UIMsg600")); // NOI18N
		pulsanteCancellaTutti
				.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		pulsanteCancellaTutti
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						pulsanteCancellaTuttiActionPerformed(evt);
					}
				});

		txCognome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txCognomeActionPerformed(evt);
			}
		});

		pulsanteOK.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/pulsanti/iconainseriscirossa.png"))); // NOI18N
		pulsanteOK.setText("OK");
		pulsanteOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pulsanteOKActionPerformed(evt);
			}
		});

		jLabel21.setText(Fc.MessageBundle("UIMsg620")); // NOI18N

		jLabel22.setText(Fc.MessageBundle("UIMsg630")); // NOI18N

		txInfo.setEditable(false);
		txInfo.setBackground(new java.awt.Color(240, 240, 240));
		txInfo.setLineWrap(true);
		txInfo.setText(Fc.MessageBundle("UIMsg610")); // NOI18N
		jScrollPane1.setViewportView(txInfo);

		javax.swing.GroupLayout pannelloModificaLayout = new javax.swing.GroupLayout(
				pannelloModifica);
		pannelloModifica.setLayout(pannelloModificaLayout);
		pannelloModificaLayout
				.setHorizontalGroup(pannelloModificaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pannelloModificaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												pannelloModificaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																pannelloModificaLayout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				11,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				txID)
																		.addGap(233,
																				233,
																				233))
														.addComponent(
																pulsanteOK,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																txCognome,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																txNome,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																pannelloModificaLayout
																		.createSequentialGroup()
																		.addGroup(
																				pannelloModificaLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel21)
																						.addComponent(
																								jLabel22))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))));
		pannelloModificaLayout
				.setVerticalGroup(pannelloModificaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pannelloModificaLayout
										.createSequentialGroup()
										.addGroup(
												pannelloModificaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(txID))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel21)
										.addGap(1, 1, 1)
										.addComponent(
												txNome,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel22)
										.addGap(1, 1, 1)
										.addComponent(
												txCognome,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												17, Short.MAX_VALUE)
										.addComponent(pulsanteOK)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(pannelloModifica,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pulsanteCancellaTutti,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pulsanteCancella,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pulsanteModifica,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(pulsanteAggiungi,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(pulsanteAggiungi)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pulsanteModifica)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pulsanteCancella)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(pulsanteCancellaTutti)
										.addGap(18, 18, 18)
										.addComponent(
												pannelloModifica,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(0, 0, 0)));

		jButtonApriPianificatore.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/Home.png"))); // NOI18N
		jButtonApriPianificatore.setToolTipText(Fc.MessageBundle("UIMsg95")); // NOI18N
		jButtonApriPianificatore
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPianificatoreActionPerformed(evt);
					}
				});

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setText(Fc.MessageBundle("UIMsg560")); // NOI18N

		jButtonApriInterventi
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInterventi.png"))); // NOI18N
		jButtonApriInterventi.setToolTipText(Fc.MessageBundle("UIMsg90")); // NOI18N
		jButtonApriInterventi
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriInterventiActionPerformed(evt);
					}
				});

		tabellaInfermieri.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		tabellaInfermieri
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane8.setViewportView(tabellaInfermieri);

		jButtonApriInfermieri
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInfermieri.png"))); // NOI18N
		jButtonApriInfermieri.setEnabled(false);
		jButtonApriInfermieri.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriInfermieri
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriInfermieriActionPerformed(evt);
					}
				});

		jButtonApriPazienti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaPazienti.png"))); // NOI18N
		jButtonApriPazienti.setToolTipText(Fc.MessageBundle("UIMsg70")); // NOI18N
		jButtonApriPazienti.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriPazienti
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPazientiActionPerformed(evt);
					}
				});

		jButtonApriPatologie
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaPatologie.png"))); // NOI18N
		jButtonApriPatologie.setToolTipText(Fc.MessageBundle("UIMsg65")); // NOI18N
		jButtonApriPatologie
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPatologieActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		immagineTestataInfermieri)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		123,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jButtonApriPatologie,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		33,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriPazienti,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriInfermieri,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriInterventi,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		33,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButtonApriPianificatore,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		33,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane8,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		382,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(19, 19, 19)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						immagineTestataInfermieri,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel1))
																.addGap(10, 10,
																		10))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButtonApriPianificatore,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriInterventi,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriInfermieri,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriPazienti,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButtonApriPatologie,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jScrollPane8,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														437,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(25, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Pulsante ok action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteOKActionPerformed
		if (modalita == Modalita.aggiungi) {
			// Aggiunta infermiere
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			// par = new ArrayList<Object>();
			par.add("String");
			par.add((Object) txNome.getText());
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) txCognome.getText());
			parametri.add(par);

			iFc.processRequest("creaInfermiere", parametri);

		} else if (modalita == Modalita.modifica
				&& JOptionPane.showConfirmDialog(null,
						Fc.MessageBundle("ConfirmMsg150"),
						Fc.MessageBundle("ConfirmMsg10"),
						JOptionPane.OK_CANCEL_OPTION,
						JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {

			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			// par = new ArrayList<Object>();
			par.add("int");
			par.add((Object) Integer.valueOf(txID.getText()));
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) txNome.getText());
			parametri.add(par);

			par = new ArrayList<>();
			par.add("String");
			par.add((Object) txCognome.getText());
			parametri.add(par);

			iFc.processRequest("modificaInfermiere", parametri);
		}
		// Aggiornamento tabella
		aggiornaTabella();
		setAggiungiInfermiere();
	}// GEN-LAST:event_pulsanteOKActionPerformed

	/**
	 * Pulsante aggiungi action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteAggiungiActionPerformed
		if (modalita == Modalita.aggiungi) {
			JOptionPane.showMessageDialog(null,
					Fc.MessageBundle("MsgDialog1940"),
					Fc.MessageBundle("MsgDialog4"),
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			setAggiungiInfermiere();
		}// GEN-LAST:event_pulsanteAggiungiActionPerformed
	}

	/**
	 * Pulsante modifica action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteModificaActionPerformed

		setModificaInfermiere();
	}// GEN-LAST:event_pulsanteModificaActionPerformed

	/**
	 * Pulsante cancella action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteCancellaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteCancellaActionPerformed

		if (tabellaInfermieri.getSelectedRow() == -1) {
			JOptionPane.showMessageDialog(
					this,
					Fc.MessageBundle("MsgDialog165") + "\n"
							+ Fc.MessageBundle("MsgDialog20"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);
		} else {
			if (JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg160"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
				// Recupero ID
				Object id = tabellaInfermieri.getValueAt(tabellaInfermieri
						.getSelectedRow(), tabellaInfermieri.getColumnModel()
						.getColumnIndex("ID"));

				// Cancellazione
				// ADISysController.cancellaInfermiere(idInt);
				ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
				ArrayList<Object> par = new ArrayList<>();

				// par = new ArrayList<Object>();
				par.add("int");
				par.add(id);
				parametri.add(par);

				iFc.processRequest("cancellaInfermiere", parametri);
				// Aggiornamento tabella
				aggiornaTabella();
			}
		}
	}// GEN-LAST:event_pulsanteCancellaActionPerformed

	/**
	 * Pulsante cancella tutti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void pulsanteCancellaTuttiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pulsanteCancellaTuttiActionPerformed
		// ADISysController.cancellaTuttiInfermieri();
		if (JOptionPane.showConfirmDialog(null,
				Fc.MessageBundle("ConfirmMsg170"),
				Fc.MessageBundle("ConfirmMsg10"), JOptionPane.OK_CANCEL_OPTION,
				JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {

			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			iFc.processRequest("cancellaTuttiInfermieri", parametri);
		}
	}// GEN-LAST:event_pulsanteCancellaTuttiActionPerformed

	/**
	 * Form window activated.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		aggiornaTabella();
	}// GEN-LAST:event_formWindowActivated

	/**
	 * Tx cognome action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void txCognomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txCognomeActionPerformed
		//
	}// GEN-LAST:event_txCognomeActionPerformed

	/**
	 * J button apri pianificatore action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPianificatoreActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPianificatoreActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg25"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			setVisible(false);
		}
	}// GEN-LAST:event_jButtonApriPianificatoreActionPerformed

	/**
	 * J button apri interventi action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriInterventiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriInterventiActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg43"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			iFc.processRequest("visualizzaEditorInterventi",
					new ArrayList<ArrayList<Object>>());
			this.setVisible(false);
		}
	}// GEN-LAST:event_jButtonApriInterventiActionPerformed

	/**
	 * Form window closing.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		int result = 0;
		if (!fieldsAreEmpty())
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg35"), Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
		else
			result = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg30"), Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

		if (result == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
	}// GEN-LAST:event_formWindowClosing

	/**
	 * J button apri pazienti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPazientiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPazientiActionPerformed
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg15"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			setVisible(false);
			iFc.processRequest("visualizzaEditorPazienti",
					new ArrayList<ArrayList<Object>>());
		}
	}// GEN-LAST:event_jButtonApriPazientiActionPerformed

	/**
	 * J button apri patologie action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPatologieActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPatologieActionPerformed
		//
		int visible = 0;
		if (!fieldsAreEmpty()) {
			visible = JOptionPane.showConfirmDialog(null,
					Fc.MessageBundle("ConfirmMsg15"),
					Fc.MessageBundle("ConfirmMsg10"),
					JOptionPane.OK_CANCEL_OPTION);
		}
		if (visible == 0) {
			iFc.processRequest("visualizzaEditorPatologie",
					new ArrayList<ArrayList<Object>>());
			this.setVisible(false);
		}
	}// GEN-LAST:event_jButtonApriPatologieActionPerformed

	/**
	 * J button apri infermieri action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriInfermieriActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriInfermieriActionPerformed
		//
	}// GEN-LAST:event_jButtonApriInfermieriActionPerformed

	/**
	 * Start.
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void start(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger
					.getLogger(EditorInfermieri.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			// @Override
			public void run() {
				EditorInfermieri window = new EditorInfermieri(
						new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit()
						.getScreenSize();
				window.setLocation(new Point((risoluzioneSchermo.width - window
						.getWidth()) / 2, (risoluzioneSchermo.height - window
						.getHeight()) / 2));

				window.setVisible(true);
			}
		});
	}

	/**
	 * Aggiorna tabella.
	 */
	public void aggiornaTabella() {
		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOInfermiere> listaInfermieri = (ArrayList<TOInfermiere>) iFc
				.processRequest("getTabellaInfermieri",
						new ArrayList<ArrayList<Object>>());
		TOInfermiere toInfermiere;
		DefaultTableModel model = new DefaultTableModel();

		// Assegnazione nomi colonne tabella
		String[] headers = Fc.getTableHeaderNames("JTableEditorInfermieri");
		model.setColumnIdentifiers(headers);

		// inserimento dei transfer objects nella tabella
		int tLength = listaInfermieri.size();
		for (int i = 0; i < tLength; i++) {
			toInfermiere = listaInfermieri.get(i);
			String[] row = { String.valueOf(toInfermiere.getID()),
					toInfermiere.getNome(), toInfermiere.getCognome() };
			model.addRow(row);
		}
		tabellaInfermieri.setModel(model);
	}

	/**
	 * Sets the aggiungi infermiere.
	 */
	private void setAggiungiInfermiere() {
		// Setta la variabile modalita
		modalita = Modalita.aggiungi;

		// Setta il modulo per l'inserimento
		txID.setText("");
		txNome.setText("");
		txCognome.setText("");
		txInfo.setText(Fc.MessageBundle("MsgDialog500"));
	}

	/**
	 * Sets the modifica infermiere.
	 */
	private void setModificaInfermiere() {

		if (tabellaInfermieri.getSelectedRow() == -1) {
			JOptionPane.showMessageDialog(
					null,
					Fc.MessageBundle("MsgDialog185") + "\n"
							+ Fc.MessageBundle("MsgDialog60"),
					Fc.MessageBundle("MsgDialog6"), JOptionPane.ERROR_MESSAGE);

		} else {

			// Setta la variabile modalita
			modalita = Modalita.modifica;

			// Recupero valori ID NOME COGNOME
			String[] colonne = Fc.getTableHeaderNames("JTableEditorInfermieri");
			Object id = tabellaInfermieri.getValueAt(tabellaInfermieri
					.getSelectedRow(), tabellaInfermieri.getColumnModel()
					.getColumnIndex(colonne[0]));
			Object nome = tabellaInfermieri.getValueAt(tabellaInfermieri
					.getSelectedRow(), tabellaInfermieri.getColumnModel()
					.getColumnIndex(colonne[1]));
			Object cognome = tabellaInfermieri.getValueAt(tabellaInfermieri
					.getSelectedRow(), tabellaInfermieri.getColumnModel()
					.getColumnIndex(colonne[2]));

			// Setta il modulo per l'inserimento
			txID.setText(String.valueOf(id));
			txNome.setText(String.valueOf(nome));
			txCognome.setText(String.valueOf(cognome));
			txInfo.setText(Fc.MessageBundle("MsgDialog510"));
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The immagine testata infermieri. */
	private javax.swing.JLabel immagineTestataInfermieri;

	/** The j button apri infermieri. */
	private javax.swing.JButton jButtonApriInfermieri;

	/** The j button apri interventi. */
	private javax.swing.JButton jButtonApriInterventi;

	/** The j button apri patologie. */
	private javax.swing.JButton jButtonApriPatologie;

	/** The j button apri pazienti. */
	private javax.swing.JButton jButtonApriPazienti;

	/** The j button apri pianificatore. */
	private javax.swing.JButton jButtonApriPianificatore;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The j label2. */
	private javax.swing.JLabel jLabel2;

	/** The j label21. */
	private javax.swing.JLabel jLabel21;

	/** The j label22. */
	private javax.swing.JLabel jLabel22;

	/** The j panel1. */
	private javax.swing.JPanel jPanel1;

	/** The j scroll pane1. */
	private javax.swing.JScrollPane jScrollPane1;

	/** The j scroll pane8. */
	private javax.swing.JScrollPane jScrollPane8;

	/** The pannello modifica. */
	private javax.swing.JPanel pannelloModifica;

	/** The pulsante aggiungi. */
	private javax.swing.JButton pulsanteAggiungi;

	/** The pulsante cancella. */
	private javax.swing.JButton pulsanteCancella;

	/** The pulsante cancella tutti. */
	private javax.swing.JButton pulsanteCancellaTutti;

	/** The pulsante modifica. */
	private javax.swing.JButton pulsanteModifica;

	/** The pulsante ok. */
	private javax.swing.JButton pulsanteOK;

	/** The tabella infermieri. */
	private javax.swing.JTable tabellaInfermieri;

	/** The tx cognome. */
	private javax.swing.JTextField txCognome;

	/** The tx id. */
	private javax.swing.JLabel txID;

	/** The tx info. */
	private javax.swing.JTextArea txInfo;

	/** The tx nome. */
	private javax.swing.JTextField txNome;

	// End of variables declaration//GEN-END:variables

	/**
	 * The Enum Modalita.
	 */
	private enum Modalita {

		/** The aggiungi. */
		aggiungi,
		/** The modifica. */
		modifica
	};

	/** The modalita. */
	private Modalita modalita;

	/**
	 * Fields are empty.
	 * 
	 * @return true, if successful
	 */
	private boolean fieldsAreEmpty() {
		if (txNome.getText().isEmpty() && txCognome.getText().isEmpty())
			return true;
		else
			return false;
	}

}
