/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adisys.server.gui;

import adisys.server.business.TOInfermiere;
import adisys.server.business.TOIntervento;
import adisys.server.business.TOPaziente;
import adisys.server.presentation.frontController.Fc;
import adisys.server.presentation.frontController.FrontController;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * The Class Pianificatore.
 * Istanzia la finestra principale contenente la visualizzazione globale 
 * dei dati di pazienti, infermieri ed interventi. Dispone di menu che 
 * richiamano tramite il Front Controller (metodo getBoundary) 
 * le finestre di dialogo destinate all’aggiornamento dei dati (Editor), 
 * all’esportazione del file di scambio (DialogoEsportazione) e alla sua 
 * importazione per la verifica (DialogoVerifica). 
 * Pianificatore dispone anche della possibilità di cambiare lingua.
 * 
 */
public class Pianificatore extends javax.swing.JFrame {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The i fc. */
	private FrontController iFc = Fc.getInstance();

	/**
	 * Creates new form ADISysGUI.
	 */
	public Pianificatore() {
		initComponents();
		aggiornaTabelle();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	@SuppressWarnings("deprecation")
	private void initComponents() {

		etichettaLogo = new javax.swing.JLabel();
		intestazione = new javax.swing.JLabel();
		jSplitPane1 = new javax.swing.JSplitPane();
		jSplitPane2 = new javax.swing.JSplitPane();
		jPanel3 = new javax.swing.JPanel();
		labelPazienti = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tabellaPazienti = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		labelInfermieri = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabellaInfermieri = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		labelInterventi = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		tabellaInterventi = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jButtonApriPianificatore = new javax.swing.JButton();
		jButtonApriInterventi = new javax.swing.JButton();
		jButtonApriInfermieri = new javax.swing.JButton();
		jButtonApriPazienti = new javax.swing.JButton();
		jButtonApriPatologie = new javax.swing.JButton();
		barraDeiMenu = new javax.swing.JMenuBar();
		menuModifica = new javax.swing.JMenu();
		menuApriPazienti = new javax.swing.JMenuItem();
		menuApriInfermieri = new javax.swing.JMenuItem();
		menuApriInterventi = new javax.swing.JMenuItem();
		jMenuItem1 = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();
		menuAggiornaTabelle = new javax.swing.JMenuItem();
		menuFile = new javax.swing.JMenu();
		menuEsportazione = new javax.swing.JMenuItem();
		menuVerifica = new javax.swing.JMenu();
		menuVerificaDati = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenuLinguaItaliano = new javax.swing.JMenuItem();
		jMenuLinguaInglese = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("ADISys - Pianificazione giornaliera");
		setBounds(new java.awt.Rectangle(0, 0, 0, 0));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMinimumSize(new java.awt.Dimension(800, 600));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		etichettaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/decorazioniFinestre/adisyssrvflat.png"))); // NOI18N

		intestazione.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/decorazioniFinestre/Pianificazione.png"))); // NOI18N

		jSplitPane1.setDividerLocation(200);
		jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		jSplitPane1.setPreferredSize(new java.awt.Dimension(500, 500));

		jSplitPane2.setBorder(null);
		jSplitPane2.setDividerLocation(380);
		jSplitPane2.setAutoscrolls(true);

		labelPazienti.setFont(labelPazienti.getFont().deriveFont(
				labelPazienti.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelPazienti.setForeground(new java.awt.Color(255, 255, 255));
		labelPazienti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelPazienti.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/barre/Verde.png"))); // NOI18N
		labelPazienti.setText(Fc.MessageBundle("UIMsg10")); // NOI18N
		labelPazienti
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		tabellaPazienti.setAutoCreateRowSorter(true);
		tabellaPazienti.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] {

				}));
		tabellaPazienti
				.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		tabellaPazienti.setNextFocusableComponent(tabellaInterventi);
		tabellaPazienti
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaPazienti.getTableHeader().setReorderingAllowed(false);
		tabellaPazienti.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				showInfoPaziente(evt);
			}
		});
		tabellaPazienti.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				tabelleKeyPressed(evt);
			}
		});
		jScrollPane2.setViewportView(tabellaPazienti);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel3Layout.createSequentialGroup()
								.addComponent(labelPazienti)
								.addGap(0, 85, Short.MAX_VALUE))
				.addComponent(jScrollPane2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 0,
						Short.MAX_VALUE));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(labelPazienti)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												173, Short.MAX_VALUE)));

		jSplitPane2.setLeftComponent(jPanel3);

		labelInfermieri.setFont(labelInfermieri.getFont().deriveFont(
				labelInfermieri.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelInfermieri.setForeground(new java.awt.Color(255, 255, 255));
		labelInfermieri
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelInfermieri.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/barre/Rossa.png"))); // NOI18N
		labelInfermieri.setText(Fc.MessageBundle("UIMsg20")); // NOI18N
		labelInfermieri
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		tabellaInfermieri.setAutoCreateRowSorter(true);
		tabellaInfermieri.setName("Pazienti"); // NOI18N
		tabellaInfermieri.setNextFocusableComponent(tabellaInfermieri);
		tabellaInfermieri
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaInfermieri.getTableHeader().setReorderingAllowed(false);
		tabellaInfermieri.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				shoInfoInfermiere(evt);
			}
		});
		tabellaInfermieri.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				tabelleKeyPressed(evt);
			}
		});
		jScrollPane1.setViewportView(tabellaInfermieri);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 0,
						Short.MAX_VALUE)
				.addGroup(
						jPanel2Layout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(labelInfermieri)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(labelInfermieri)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												173, Short.MAX_VALUE)));

		jSplitPane2.setRightComponent(jPanel2);

		jSplitPane1.setLeftComponent(jSplitPane2);

		labelInterventi.setFont(labelInterventi.getFont().deriveFont(
				labelInterventi.getFont().getStyle() | java.awt.Font.BOLD, 14));
		labelInterventi.setForeground(new java.awt.Color(255, 255, 255));
		labelInterventi
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelInterventi.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/barre/Azzurra.png"))); // NOI18N
		labelInterventi.setText(Fc.MessageBundle("UIMsg30")); // NOI18N
		labelInterventi
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		tabellaInterventi.setAutoCreateRowSorter(true);
		tabellaInterventi.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] {

				}));
		tabellaInterventi
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		tabellaInterventi.getTableHeader().setReorderingAllowed(false);
		tabellaInterventi.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				showInfoIntervento(evt);
			}
		});
		tabellaInterventi.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				tabelleKeyPressed(evt);
			}
		});
		jScrollPane3.setViewportView(tabellaInterventi);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane3,
						javax.swing.GroupLayout.DEFAULT_SIZE, 625,
						Short.MAX_VALUE)
				.addGroup(
						jPanel1Layout.createSequentialGroup()
								.addComponent(labelInterventi)
								.addGap(0, 0, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												labelInterventi,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												192, Short.MAX_VALUE)));

		jSplitPane1.setRightComponent(jPanel1);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 102, 0));
		jLabel1.setText(Fc.MessageBundle("UIMsg720")); // NOI18N

		jButtonApriPianificatore.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/Home.png"))); // NOI18N
		jButtonApriPianificatore.setEnabled(false);
		jButtonApriPianificatore
				.setPreferredSize(new java.awt.Dimension(33, 33));

		jButtonApriInterventi
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInterventi.png"))); // NOI18N
		jButtonApriInterventi.setToolTipText(Fc.MessageBundle("UIMsg90")); // NOI18N
		jButtonApriInterventi.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriInterventi
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriInterventiActionPerformed(evt);
					}
				});

		jButtonApriInfermieri
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInfermieri.png"))); // NOI18N
		jButtonApriInfermieri.setToolTipText(Fc.MessageBundle("UIMsg80")); // NOI18N
		jButtonApriInfermieri.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriInfermieri
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriInfermieriActionPerformed(evt);
					}
				});

		jButtonApriPazienti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaPazienti.png"))); // NOI18N
		jButtonApriPazienti.setToolTipText(Fc.MessageBundle("UIMsg70")); // NOI18N
		jButtonApriPazienti.setPreferredSize(new java.awt.Dimension(33, 33));
		jButtonApriPazienti
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPazientiActionPerformed(evt);
					}
				});

		jButtonApriPatologie
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaPatologie.png"))); // NOI18N
		jButtonApriPatologie.setToolTipText(Fc.MessageBundle("UIMsg65")); // NOI18N
		jButtonApriPatologie
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonApriPatologieActionPerformed(evt);
					}
				});

		barraDeiMenu.setRequestFocusEnabled(false);

		menuModifica.setText(Fc.MessageBundle("UIMsg40")); // NOI18N

		menuApriPazienti.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_Q,
				java.awt.event.InputEvent.CTRL_MASK));
		menuApriPazienti.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaPazienti.png"))); // NOI18N
		menuApriPazienti.setText(Fc.MessageBundle("UIMsg70")); // NOI18N
		menuApriPazienti.setToolTipText("");
		menuApriPazienti.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menuApriPazientiActionPerformed(evt);
			}
		});
		menuModifica.add(menuApriPazienti);

		menuApriInfermieri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_W,
				java.awt.event.InputEvent.CTRL_MASK));
		menuApriInfermieri
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInfermieri.png"))); // NOI18N
		menuApriInfermieri.setText(Fc.MessageBundle("UIMsg80")); // NOI18N
		menuApriInfermieri
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						menuApriInfermieriActionPerformed(evt);
					}
				});
		menuModifica.add(menuApriInfermieri);

		menuApriInterventi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_MASK));
		menuApriInterventi
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/adisys/server/img/pulsanti/IconaInterventi.png"))); // NOI18N
		menuApriInterventi.setText(Fc.MessageBundle("UIMsg90")); // NOI18N
		menuApriInterventi
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						menuApriInterventiActionPerformed(evt);
					}
				});
		menuModifica.add(menuApriInterventi);

		jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_P,
				java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/adisys/server/img/pulsanti/IconaPatologie.png"))); // NOI18N
		java.util.ResourceBundle bundle = java.util.ResourceBundle
				.getBundle("adisys/server/lang/MessagesBundle"); // NOI18N
		jMenuItem1.setText(bundle.getString("UIMsg65")); // NOI18N
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		menuModifica.add(jMenuItem1);
		menuModifica.add(jSeparator1);

		menuAggiornaTabelle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_R,
				java.awt.event.InputEvent.CTRL_MASK));
		menuAggiornaTabelle.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaAggiorna.png"))); // NOI18N
		menuAggiornaTabelle.setText(Fc.MessageBundle("UIMsg100")); // NOI18N
		menuAggiornaTabelle
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						menuAggiornaTabelleActionPerformed(evt);
					}
				});
		menuModifica.add(menuAggiornaTabelle);

		barraDeiMenu.add(menuModifica);

		menuFile.setText(Fc.MessageBundle("UIMsg50")); // NOI18N

		menuEsportazione.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_E,
				java.awt.event.InputEvent.CTRL_MASK));
		menuEsportazione.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/adisys/server/img/pulsanti/IconaEsportazione.png"))); // NOI18N
		menuEsportazione.setText(Fc.MessageBundle("UIMsg110")); // NOI18N
		menuEsportazione.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menuEsportazioneActionPerformed(evt);
			}
		});
		menuFile.add(menuEsportazione);

		barraDeiMenu.add(menuFile);

		menuVerifica.setText(Fc.MessageBundle("UIMsg60")); // NOI18N
		menuVerifica.setToolTipText("");

		menuVerificaDati.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_F,
				java.awt.event.InputEvent.CTRL_MASK));
		menuVerificaDati.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaVerifica.png"))); // NOI18N
		menuVerificaDati.setText(Fc.MessageBundle("UIMsg120")); // NOI18N
		menuVerificaDati.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				menuVerificaDatiActionPerformed(evt);
			}
		});
		menuVerifica.add(menuVerificaDati);

		barraDeiMenu.add(menuVerifica);

		jMenu1.setText("Language");

		jMenuLinguaItaliano.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaLinguaIT.png"))); // NOI18N
		jMenuLinguaItaliano.setText("Italiano");
		jMenuLinguaItaliano
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuLinguaItalianoActionPerformed(evt);
					}
				});
		jMenu1.add(jMenuLinguaItaliano);

		jMenuLinguaInglese.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/adisys/server/img/pulsanti/IconaLinguaEN.png"))); // NOI18N
		jMenuLinguaInglese.setText("English");
		jMenuLinguaInglese
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuLinguaIngleseActionPerformed(evt);
					}
				});
		jMenu1.add(jMenuLinguaInglese);

		barraDeiMenu.add(jMenu1);

		setJMenuBar(barraDeiMenu);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jSplitPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		intestazione)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		178,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		209,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jButtonApriPatologie,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										33,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButtonApriPazienti,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButtonApriInfermieri,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButtonApriInterventi,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButtonApriPianificatore,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addContainerGap())
																				.addComponent(
																						etichettaLogo,
																						javax.swing.GroupLayout.Alignment.TRAILING))))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(4, 4, 4)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		etichettaLogo,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		23,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										jButtonApriPianificatore,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jButtonApriInterventi,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jButtonApriInfermieri,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jButtonApriPazienti,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addComponent(
																						jButtonApriPatologie,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						33,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		intestazione,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSplitPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										424, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Menu apri interventi action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuApriInterventiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuApriInterventiActionPerformed

		// ADISysController.visualizzaEditorInterventi();
		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		iFc.processRequest("visualizzaEditorInterventi", parametri);
	}// GEN-LAST:event_menuApriInterventiActionPerformed

	/**
	 * Menu apri pazienti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuApriPazientiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuApriPazientiActionPerformed
		iFc.processRequest("visualizzaEditorPazienti",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_menuApriPazientiActionPerformed

	/**
	 * Menu apri infermieri action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuApriInfermieriActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuApriInfermieriActionPerformed
		iFc.processRequest("visualizzaEditorInfermieri",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_menuApriInfermieriActionPerformed

	/**
	 * Menu verifica dati action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuVerificaDatiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuVerificaDatiActionPerformed

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		iFc.processRequest("visualizzaDialogoVerifica", parametri);
	}// GEN-LAST:event_menuVerificaDatiActionPerformed

	/**
	 * Menu aggiorna tabelle action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuAggiornaTabelleActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuAggiornaTabelleActionPerformed
		int visible = JOptionPane.showConfirmDialog(null,
				Fc.MessageBundle("ConfirmMsg50"),
				Fc.MessageBundle("ConfirmMsg10"), JOptionPane.OK_CANCEL_OPTION);
		if (visible == 0) {
			aggiornaTabelle();
		}

	}// GEN-LAST:event_menuAggiornaTabelleActionPerformed

	/**
	 * Form window activated.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		System.out.println(Fc.MessageBundle("MsgDialog670"));
		aggiornaTabelle();

	}// GEN-LAST:event_formWindowActivated

	/**
	 * Menu esportazione action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void menuEsportazioneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuEsportazioneActionPerformed

		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		iFc.processRequest("visualizzaDialogoEsportazione", parametri);
	}// GEN-LAST:event_menuEsportazioneActionPerformed

	/**
	 * J menu lingua italiano action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jMenuLinguaItalianoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuLinguaItalianoActionPerformed
		adisys.server.presentation.frontController.Fc.setLocale("it", "IT");
		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		iFc.processRequest("visualizzaPianificatore", parametri);
		this.setVisible(false);
	}// GEN-LAST:event_jMenuLinguaItalianoActionPerformed

	/**
	 * J menu lingua inglese action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jMenuLinguaIngleseActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuLinguaIngleseActionPerformed
		adisys.server.presentation.frontController.Fc.setLocale("en", "US");
		ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
		iFc.processRequest("visualizzaPianificatore", parametri);
		this.setVisible(false);
	}// GEN-LAST:event_jMenuLinguaIngleseActionPerformed

	/**
	 * Form window closing.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		int result = JOptionPane.showConfirmDialog(null,
				Fc.MessageBundle("ConfirmMsg30"), Fc.MessageBundle("ConfirmMsg10"),
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		if (result == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
	}// GEN-LAST:event_formWindowClosing

	/**
	 * Tabelle key pressed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void tabelleKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabelleKeyPressed
	}// GEN-LAST:event_tabelleKeyPressed

	/**
	 * Show info paziente.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void showInfoPaziente(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_showInfoPaziente
		// Recupero valore ID
		int colonnaID = tabellaPazienti.getColumnModel().getColumnIndex("ID");
		int selectedID = Integer.valueOf(String.valueOf(tabellaPazienti
				.getValueAt(tabellaPazienti.getSelectedRow(), colonnaID)));

		// Recupero informazioni
		if (selectedID != -1) {
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			par.add("int");
			par.add((Object) selectedID);
			parametri.add(par);

			String msg = (String) iFc.processRequest("showInfoPaziente",
					parametri);
			JOptionPane.showMessageDialog(null, msg);
		}
	}// GEN-LAST:event_showInfoPaziente

	/**
	 * Sho info infermiere.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void shoInfoInfermiere(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_shoInfoInfermiere
		// Recupero valore ID
		int colonnaID = tabellaInfermieri.getColumnModel().getColumnIndex("ID");
		int selectedID = Integer.valueOf(String.valueOf(tabellaInfermieri
				.getValueAt(tabellaInfermieri.getSelectedRow(), colonnaID)));

		// Recupero informazioni
		if (selectedID != -1) {
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			par.add("int");
			par.add((Object) selectedID);
			parametri.add(par);

			String msg = (String) iFc.processRequest("showInfoInfermiere",
					parametri);
			JOptionPane.showMessageDialog(null, msg);
		}
	}// GEN-LAST:event_shoInfoInfermiere

	/**
	 * Show info intervento.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void showInfoIntervento(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_showInfoIntervento
		// Recupero valore ID
		int colonnaID = tabellaInterventi.getColumnModel().getColumnIndex("ID");
		int selectedID = Integer.valueOf(String.valueOf(tabellaInterventi
				.getValueAt(tabellaInterventi.getSelectedRow(), colonnaID)));

		// Recupero informazioni
		if (selectedID != -1) {
			ArrayList<ArrayList<Object>> parametri = new ArrayList<>();
			ArrayList<Object> par = new ArrayList<>();

			par.add("int");
			par.add((Object) selectedID);
			parametri.add(par);

			String msg = (String) iFc.processRequest("showInfoIntervento",
					parametri);
			JOptionPane.showMessageDialog(null, msg);
		}
	}// GEN-LAST:event_showInfoIntervento

	/**
	 * J button apri pazienti action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPazientiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPazientiActionPerformed
		iFc.processRequest("visualizzaEditorPazienti",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_jButtonApriPazientiActionPerformed

	/**
	 * J button apri infermieri action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriInfermieriActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriInfermieriActionPerformed
		iFc.processRequest("visualizzaEditorInfermieri",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_jButtonApriInfermieriActionPerformed

	/**
	 * J button apri interventi action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriInterventiActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriInterventiActionPerformed
		iFc.processRequest("visualizzaEditorInterventi",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_jButtonApriInterventiActionPerformed

	/**
	 * J menu item1 action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		iFc.processRequest("visualizzaEditorPatologie",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * J button apri patologie action performed.
	 * 
	 * @param evt
	 *            the evt
	 */
	private void jButtonApriPatologieActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonApriPatologieActionPerformed
		iFc.processRequest("visualizzaEditorPatologie",
				new ArrayList<ArrayList<Object>>());
	}// GEN-LAST:event_jButtonApriPatologieActionPerformed

	/**
	 * Start.
	 */
	public static void start() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Pianificatore.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			// @Override
			public void run() {
				Pianificatore window = new Pianificatore();
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit()
						.getScreenSize();
				window.setLocation(new Point((risoluzioneSchermo.width - window
						.getWidth()) / 2, (risoluzioneSchermo.height - window
						.getHeight()) / 2));
				window.setVisible(true);
			}
		});

	}

	/**
	 * Aggiorna tabelle.
	 */
	private void aggiornaTabelle() {
		// AGGIORNAMENTO DELLE TABELLE
		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOPaziente> listaPazienti = (ArrayList<TOPaziente>) iFc
				.processRequest("getTabellaPazienti",
						new ArrayList<ArrayList<Object>>());
		TOPaziente toPaziente;
		DefaultTableModel modelPaziente = new DefaultTableModel();

		// Assegnazione nomi colonne tabella
		String[] headersPaziente = Fc
				.getTableHeaderNames("JTableEditorInterventi-Pazienti");
		modelPaziente.setColumnIdentifiers(headersPaziente);

		// inserimento dei transfer objects nella tabella
		int tLengthPaziente = 0;
		if (listaPazienti != null)
			tLengthPaziente = listaPazienti.size();
		for (int i = 0; i < tLengthPaziente; i++) {
			toPaziente = listaPazienti.get(i);
			String[] row = { String.valueOf(toPaziente.getID()),
					toPaziente.getNome(), toPaziente.getCognome(),
					toPaziente.getDataNascita("yyyy-MM-dd") };
			modelPaziente.addRow(row);
		}
		tabellaPazienti.setModel(modelPaziente);

		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOInfermiere> listaInfermieri = (ArrayList<TOInfermiere>) iFc
				.processRequest("getTabellaInfoInfermieri",
						new ArrayList<ArrayList<Object>>());
		TOInfermiere toInfermiere;
		DefaultTableModel modelInfermiere = new DefaultTableModel();

		// Assegnazione nomi colonne tabella
		String[] headersInfermiere = Fc
				.getTableHeaderNames("JTablePianificatore-Infermieri");
		modelInfermiere.setColumnIdentifiers(headersInfermiere);

		// inserimento dei transfer objects nella tabella
		int tLengthInfermieri = 0;
		if (listaInfermieri != null)
			tLengthInfermieri = listaInfermieri.size();
		for (int i = 0; i < tLengthInfermieri; i++) {
			toInfermiere = listaInfermieri.get(i);
			String[] row = { String.valueOf(toInfermiere.getID()),
					toInfermiere.getNome(), toInfermiere.getCognome(),
					String.valueOf(toInfermiere.getNumInterventi()) };
			modelInfermiere.addRow(row);
		}
		tabellaInfermieri.setModel(modelInfermiere);

		// Popolamento dati
		@SuppressWarnings("unchecked")
		ArrayList<TOIntervento> listaInterventi = (ArrayList<TOIntervento>) iFc
				.processRequest("getTabellaVisualizzazioneInterventi",
						new ArrayList<ArrayList<Object>>());
		TOIntervento toIntervento;

		DefaultTableModel modelIntervento = new DefaultTableModel();

		// Assegnazione nomi colonne tabella interventi
		String[] headersIntervento = Fc
				.getTableHeaderNames("JTablePianificatore-Interventi");
		modelIntervento.setColumnIdentifiers(headersIntervento);

		// inserimento dei transfer objects nella tabella interventi
		int tLengthIntervento = 0;
		if (listaInterventi != null)
			tLengthIntervento = listaInterventi.size();
		for (int i = 0; i < tLengthIntervento; i++) {
			toIntervento = listaInterventi.get(i);
			String[] row = { String.valueOf(toIntervento.getID()),
					toIntervento.getCognomeInfermiere(),
					toIntervento.getNomePaziente(),
					toIntervento.getCognomePaziente(),
					toIntervento.getData("yyyy-MM-dd"),
					toIntervento.getOraInizio("HH:mm:ss"),
					toIntervento.getCitta(), toIntervento.getCivico() };
			modelIntervento.addRow(row);
		}
		tabellaInterventi.setModel(modelIntervento);

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The barra dei menu. */
	private javax.swing.JMenuBar barraDeiMenu;

	/** The etichetta logo. */
	private javax.swing.JLabel etichettaLogo;

	/** The intestazione. */
	private javax.swing.JLabel intestazione;

	/** The j button apri infermieri. */
	private javax.swing.JButton jButtonApriInfermieri;

	/** The j button apri interventi. */
	private javax.swing.JButton jButtonApriInterventi;

	/** The j button apri patologie. */
	private javax.swing.JButton jButtonApriPatologie;

	/** The j button apri pazienti. */
	private javax.swing.JButton jButtonApriPazienti;

	/** The j button apri pianificatore. */
	private javax.swing.JButton jButtonApriPianificatore;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The j menu1. */
	private javax.swing.JMenu jMenu1;

	/** The j menu item1. */
	private javax.swing.JMenuItem jMenuItem1;

	/** The j menu lingua inglese. */
	private javax.swing.JMenuItem jMenuLinguaInglese;

	/** The j menu lingua italiano. */
	private javax.swing.JMenuItem jMenuLinguaItaliano;

	/** The j panel1. */
	private javax.swing.JPanel jPanel1;

	/** The j panel2. */
	private javax.swing.JPanel jPanel2;

	/** The j panel3. */
	private javax.swing.JPanel jPanel3;

	/** The j scroll pane1. */
	private javax.swing.JScrollPane jScrollPane1;

	/** The j scroll pane2. */
	private javax.swing.JScrollPane jScrollPane2;

	/** The j scroll pane3. */
	private javax.swing.JScrollPane jScrollPane3;

	/** The j separator1. */
	private javax.swing.JPopupMenu.Separator jSeparator1;

	/** The j split pane1. */
	private javax.swing.JSplitPane jSplitPane1;

	/** The j split pane2. */
	private javax.swing.JSplitPane jSplitPane2;

	/** The label infermieri. */
	private javax.swing.JLabel labelInfermieri;

	/** The label interventi. */
	private javax.swing.JLabel labelInterventi;

	/** The label pazienti. */
	private javax.swing.JLabel labelPazienti;

	/** The menu aggiorna tabelle. */
	private javax.swing.JMenuItem menuAggiornaTabelle;

	/** The menu apri infermieri. */
	private javax.swing.JMenuItem menuApriInfermieri;

	/** The menu apri interventi. */
	private javax.swing.JMenuItem menuApriInterventi;

	/** The menu apri pazienti. */
	private javax.swing.JMenuItem menuApriPazienti;

	/** The menu esportazione. */
	private javax.swing.JMenuItem menuEsportazione;

	/** The menu file. */
	private javax.swing.JMenu menuFile;

	/** The menu modifica. */
	private javax.swing.JMenu menuModifica;

	/** The menu verifica. */
	private javax.swing.JMenu menuVerifica;

	/** The menu verifica dati. */
	private javax.swing.JMenuItem menuVerificaDati;

	/** The tabella infermieri. */
	private javax.swing.JTable tabellaInfermieri;

	/** The tabella interventi. */
	private javax.swing.JTable tabellaInterventi;

	/** The tabella pazienti. */
	private javax.swing.JTable tabellaPazienti;
	// End of variables declaration//GEN-END:variables
}
